Repository unelmacoin/unelma-code-translate, pull requests merged in 2025-03, with the labels that each got.

#78 Up 262 remove gpt4 0125 preview
  components/ModelSelect.tsx
  config/.firebase.ts.swp
Labels: model, modifcation

#81 Sign up with google
  components/Nav.tsx
  components/RestrictedModelModal.tsx
  contexts/AuthContext.tsx
  contexts/ThemeContext.tsx
  pages/_app.tsx
  pages/index.tsx
  pages/login.tsx
  pages/signup.tsx
  pages/signupwithemail.tsx
  public/google.svg
Labels: enhancement, modifcation

#82 Forget password
  components/Nav.tsx
  components/RestrictedModelModal.tsx
  middleware/csrf.ts
  package-lock.json
  package.json
  pages/api/check-email.ts
  pages/index.tsx
  pages/login.tsx
  pages/passwordreset.tsx
  pages/signup.tsx
  pages/signupwithemail.tsx
  utils/csrf.ts
Labels: enhancement, modifcation

#83 Enhance test
  __tests__/CodeBlock.test.jsx
  __tests__/ModelSelect.test.jsx
  __tests__/TextBlock.test.jsx
  __tests__/ThemeButton.test.jsx
  components/CodeBlock.tsx
  components/TextBlock.tsx
  components/UploadImagesAndFiles.tsx
Labels: modification
